FORMAT: 1A
HOST: https://muh.io/

# Muh

Muh api provides a in memory paste service, which immediately
stores your pastes. It is optimized on low latency access.

## Gist

A gist is just the logical layer on top of snippets. 
It could also be called as a SnippetCollection.

## Gist/Snippet handling [/gists]

Creating gists, adding snippets and requesting gists.

### Fetching a Gist [GET /gists/{uuid}]

+ Parameters
    + uuid (string) - Gists unique identifier

+ Response 200 (application/json)
    + Headers
        X-Ratelimit-Hits: Amount of requests until last reset
        X-Ratelimit-Bytes: Amount of traffic (upload/download) until last reset
    + Attributes(Gist full)
    + Body

### Create a gist with snippets [POST /gists]

+ Request (application/x-www-form-urlencoded)
    + Attributes(Snippet)
    + Body
        snippets[0]paste=somerubycode&
        snippets[0]lang=ruby&
        snippets[1]paste=moarrubycode&
        snippets[1]lang=ruby
        
+ Response 201 (application/json)
    + Headers
        X-Ratelimit-Hits: Amount of requests until last reset
        X-Ratelimit-Bytes: Amount of traffic (upload/download) until last reset
    + Attributes(Gist short)
    + Body

# Data Structures

## Gist short (object)
+ gist: 
  + uuid: `2059d36c-cd5a-4271-8abd-cf184f04db7c` (string, required) - Unique gist identifier.

## Gist full (object)
+ gist: 
  + uuid: `2059d36c-cd5a-4271-8abd-cf184f04db7c` (string, required) - Unique gist identifier.
+ snippets: (array[Snippet]) - A list of snippets

## Snippet (object)
+ paste: `some ruby code` (string, required) - Raw content of paste.
+ lang: `ruby` (string, required) - Which kind of programming language the paste is.
